name: great_places
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: 6.1.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  path: ^1.9.1
  sqflite: ^2.4.2
  location: ^8.0.1
  google_maps_flutter: ^2.12.3
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
